### PR TITLE
Travis-CI integration

### PR DESCRIPTION
**Pull request by krlmlr**
- Ignores
- .travis.yml file

### CODE REVIEW

**Comment by krlmlr** [comment]
Same as hadley/rappdirs#6.

**Comment by krlmlr** [comment]
The multi-OS feature actually [seems to work](https://travis-ci.org/krlmlr/rappdirs/builds/29585627), but you have to ask support@travis-ci.com to enable it (took them less than half an hour when I asked), and of course Travis-CI needs to be enabled on the repo in the first place.

**Comment by jefferis** [comment]
Hi @krlmlr, these look like useful improvements to the travis setup (didn't know you could do multi-os on free), and perfectly reasonable changes to the rstudio setup as well, but the pull request should really be against my master or @hadley's master. If you want, maybe do the pull against my master and I'll try and bundle any non-trivial changes together. 

Incidentally this feature branch actually fails spectacularly when I send it to winbuilder.

**Comment by krlmlr** [comment]
This pull is based on your feature branch, that's why I based it on your feature branch. If you merge this, your feature branch is going to be updated, no need to combine non-trivial changes anymore. I've just fixed one of the build errors -- what else does winbuilder complain about?

**Comment by jefferis** [comment]
Sorry, let me try and explain a bit better. 

0) all the important work has already been merged into master.

1) I wasn't planning to merge this feature branch with master because it is not essential and it is completely broken on windows for reasons that I have not yet understood but relate to construction of paths. Here is sample output from winbuilder:

http://win-builder.r-project.org/khY97yG9DaCz/

2) I'm probably being dense, but this feature branch is _behind_ master. When I figure out how to implement this feature properly I will then want to merge with master or rebase onto it. Your patches include changes in `README.md` (the travis urls) and `.travis.yml` (most of it) that will then cause a merge conflict when I try to merge with master because they duplicate or extend changes that have already been applied to master. So really it would be better if your pull request was against master (my master and hadley's are in sync) and we leave this feature branch alone for the time being.

Does that make sense?

**Comment by jefferis** [comment]
Or just look at https://github.com/hadley/rappdirs/network

**Comment by krlmlr** [comment]
Now I see your point. I completely overlooked that the Travis config file is already in place, sorry for that.

However, from the network, it seems to me that 877e1db3b43a8 is the only change that's not yet in `master`. Why? Moving the tests to `tests/testthat` makes perfect sense to me -- and the reason why the tests fail might just be that they are not designed for Windows. Do you want to fix the tests, or shall I take a look?

**Comment by krlmlr** [comment]
See hadley/rappdirs#7.

**Comment by jefferis** [comment]
> However, from the network, it seems to me that 877e1db is the only change that's not yet in master. Why? Moving the tests to tests/testthat makes perfect sense to me -- and the reason why the tests fail might just be that they are not designed for Windows. Do you want to fix the tests, or shall I take a look? 

Thanks. You're right that is the appropriate location. I'd be delighted if you had a look because I don't have a local windows system and submitting to winbuilder has rather a long latency for iterative bug fixing. The strange thing is that the tests work fine on windows when they are at `inst/tests` but not when they are in `tests/testthat`. I think there must be some kind of aliasing of `file.path` or some related function when `test_check` runs.

**Pull request closed without merging**
